version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    groups:
      npm-patch-and-minor:
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
